# Generated by Django 5.2.17 on 2026-09-18 19:27

import crm.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.CharField(blank=True, max_length=120, verbose_name='Сфера деятельности'),
        ),
        migrations.AddField(
            model_name='client',
            name='kind',
            field=models.CharField(choices=[('person', 'Человек'), ('company', 'Компания')], default='person', max_length=10, verbose_name='Тип клиента'),
        ),
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, upload_to=crm.models.client_photo_path, verbose_name='Фото или логотип'),
        ),
        migrations.AddField(
            model_name='client',
            name='position',
            field=models.CharField(blank=True, max_length=120, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='client',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
    ]
